### ISSUE TITLE
When I run on the arm, I get encountered when I start

### ISSUE THREAD

**Issue by theqf** [socketio/socket.io-client-cpp#217]
(gdb) where
#0  0xb6d38258 in __GI_raise (sig=sig@entry=6) at ../nptl/sysdeps/unix/sysv/linux/raise.c:66
#1  0xb6d3bcd8 in __GI_abort () at abort.c:90
#2  0xb6f58708 in __gnu_cxx::__verbose_terminate_handler () at ../../../../../gcc~linaro-4.8-2013.12/libstdc++-v3/libsupc++/vterminate.cc:95
#3  0xb6f56540 in __cxxabiv1::__terminate (handler=<optimized out>) at ../../../../../gcc~linaro-4.8-2013.12/libstdc++-v3/libsupc++/eh_terminate.cc:38
#4  0xb6f56568 in std::terminate () at ../../../../../gcc~linaro-4.8-2013.12/libstdc++-v3/libsupc++/eh_terminate.cc:48
#5  0xb6f57280 in __cxxabiv1::__cxa_pure_virtual () at ../../../../../gcc~linaro-4.8-2013.12/libstdc++-v3/libsupc++/pure.cc:50
#6  0xb6faac94 in std::(anonymous namespace)::execute_native_thread_routine (__p=<optimized out>) at ../../../../../../gcc~linaro-4.8-2013.12/libstdc++-v3/src/c++11/thread.cc:84
#7  0xb6edae74 in start_thread (arg=0xaefff450) at pthread_create.c:314
#8  0xb6dd80b8 in ?? () from /lib/a9_vfpv3_neon/libc.so.6
Cannot access memory at address 0x0
#9  0xb6dd80b8 in ?? () from /lib/a9_vfpv3_neon/libc.so.6
Cannot access memory at address 0x0
Backtrace stopped: previous frame identical to this frame (corrupt stack?)

**Comment by theqf** [comment]
![image](https://user-images.githubusercontent.com/7857631/47138558-554ca000-d2ec-11e8-9eb0-a08b9cbf7b6b.png)

**Comment by theqf** [comment]
![image](https://user-images.githubusercontent.com/7857631/47138595-6e555100-d2ec-11e8-84ad-c6e24f1c47bf.png)
