### ISSUE TITLE
migration socket.io v2 to v3 stream_1.pipeline error?

### ISSUE THREAD

**Issue by Nelson-numerical-software** [socketio/socket.io-client-cpp#288]
socket.IO Migration guide said:
https://socket.io/docs/v3/migrating-from-2-x-to-3-0/index.html
`This error is probably due to your version of Node.js. The pipeline method was introduced in Node.js 10.0.0`

I tested with nodejs `14.15.4` and `12.20.1` and I have same error.
```
Server running at http://localhost:9090
/home/mcallan/Github/nelson-cloud/node_modules/socket.io/dist/index.js:271
                stream_1.pipeline(readStream, zlib_1.createGzip(), res, onError);
                         ^

TypeError: stream_1.pipeline is not a function
    at Function.sendFile (/home/mcallan/Github/nelson-cloud/node_modules/socket.io/dist/index.js:271:26)
    at Server.serve (/home/mcallan/Github/nelson-cloud/node_modules/socket.io/dist/index.js:247:16)
    at Server.srv.on (/home/mcallan/Github/nelson-cloud/node_modules/socket.io/dist/index.js:207:22)
    at Server.emit (events.js:180:13)
    at parserOnIncoming (_http_server.js:642:12)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:117:17)
```
see `https://github.com/Nelson-numerical-software/nelson-cloud/pull/9`

Some tips to resolve this trouble is welcome !!!

**Comment by darrachequesne** [comment]
Hi! I can't reproduce with a Node.js version > 10.0.0. It seems the CI build has succeeded though: https://travis-ci.org/github/Nelson-numerical-software/nelson-cloud/builds/757136285

**Comment by Nelson-numerical-software** [comment]
Fixed (forgot to do: nvm use in my term ...) Thanks
