### ISSUE TITLE
socket.io client crash when call sync_close on branch master

### ISSUE THREAD

**Issue by JinChengShi** [socketio/socket.io-client-cpp#375]
#0  0x00007f6e12d33cfc in sio::socket::impl::close() () from ../libs/libsioclient_tls.so.1
#1  0x00007f6e12d4097a in sio::client_impl::sockets_invoke_void(void (sio::socket::*)()) () from ../libs/libsioclient_tls.so.1
#2  0x00007f6e12d412fa in sio::client_impl::sync_close() () from ../libs/libsioclient_tls.so.1
#3  0x00007f6e144357e2 in irtc::conference::ConferenceSocketSignalingChannel::~ConferenceSocketSignalingChannel() () from ../libs/libirtc.so
#4  0x00007f6e14403aa5 in std::_Sp_counted_deleter<irtc::conference::ConferenceSocketSignalingChannel*, std::__shared_ptr<irtc::conference::ConferenceSocketSignalingChannel, (__gnu_cxx::_Lock_policy)2>::_Deleter<std::allocator<irtc::conference::ConferenceSocketSignalingChannel> >, std::allocator<irtc::conference::ConferenceSocketSignalingChannel>, (__gnu_cxx::_Lock_policy)2>::_M_dispose() () from ../libs/libirtc.so
#5  0x0000564a3717c02c in std::_Sp_counted_base<(__gnu_cxx::_Lock_policy)2>::_M_release() ()
#6  0x00007f6e144102d1 in irtc::conference::ConferenceClient::~ConferenceClient() () from ../libs/libirtc.so
#7  0x00007f6e144104c1 in irtc::conference::ConferenceClient::~ConferenceClient() () from ../libs/libirtc.so
#8  0x0000564a3717c02c in std::_Sp_counted_base<(__gnu_cxx::_Lock_policy)2>::_M_release() ()
#9  0x0000564a3717bec9 in std::__shared_count<(__gnu_cxx::_Lock_policy)2>::~__shared_count() ()
#10 0x0000564a3719447e in std::__shared_ptr<irtc::conference::ConferenceClient, (__gnu_cxx::_Lock_policy)2>::~__shared_ptr() ()
#11 0x0000564a3719449a in std::shared_ptr<irtc::conference::ConferenceClient>::~shared_ptr() ()
#12 0x0000564a3717de07 in CAutoTestClient::~CAutoTestClient() ()
#13 0x0000564a3717de6e in CAutoTestClient::~CAutoTestClient() ()
#14 0x0000564a371cc7ec in std::_Sp_counted_ptr<CAutoTestClient*, (__gnu_cxx::_Lock_policy)2>::_M_dispose() ()
#15 0x0000564a3717c02c in std::_Sp_counted_base<(__gnu_cxx::_Lock_policy)2>::_M_release() ()
#16 0x0000564a3717bec9 in std::__shared_count<(__gnu_cxx::_Lock_policy)2>::~__shared_count() ()
#17 0x0000564a371b888c in std::__shared_ptr<CAutoTestClient, (__gnu_cxx::_Lock_policy)2>::~__shared_ptr() ()
#18 0x0000564a371cc5aa in std::__shared_ptr<CAutoTestClient, (__gnu_cxx::_Lock_policy)2>::reset() ()
#19 0x0000564a371cbc05 in NodeTest::TearDown() ()
#20 0x0000564a372ab329 in void testing::internal::HandleSehExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) ()
#21 0x0000564a372a483d in void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) ()
#22 0x0000564a3727c48f in testing::Test::Run() ()
#23 0x0000564a3727ce14 in testing::TestInfo::Run() ()
#24 0x0000564a3727d6ba in testing::TestSuite::Run() ()
#25 0x0000564a3728c742 in testing::internal::UnitTestImpl::RunAllTests() ()
#26 0x0000564a372ac53b in bool testing::internal::HandleSehExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) ()
#27 0x0000564a372a57a9 in bool testing::internal::HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) ()
#28 0x0000564a3728af84 in testing::UnitTest::Run() ()
#29 0x0000564a372507ac in RUN_ALL_TESTS() ()
#30 0x0000564a3725071f in CUnitTest::start(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) ()
#31 0x0000564a3717bcd5 in main ()

**Comment by DraconPern** [comment]
Most likely you are running into this issue due to a race condition. see my solution https://github.com/socketio/socket.io-client-cpp/issues/254#issuecomment-627299829
